version: '3.8'

services:
  vue3:
    container_name: vue3
    build:
      context: .
      dockerfile: production.Dockerfile
      args:
        NODE_ENV_USER: production
        NODE_VERSION: 21-bookworm
    user: "1000:1000"
    command: bash -c "yarn preview"
    environment:
      - UID=1000
      - GID=1000
    ports:
      - "8080:8080"
